language: node_js
node_js:
 - 'stable'
install:
 - npm install
scripts:
  - npm install codecov -g
  - tslint -c tslint.json 'src/**/*.ts'
  - npm test
  - codecov -f coverage/*.json
after_success:
  - codecov